#!/usr/bin/env ruby
#
# $Id$
#
# Send a DNS request

require 'rubygems'
require 'racket'

include Racket
unless (ARGV.size == 3) 
  puts "Usage: #{$0} <srcip> <dstip> <domain>"
  exit
end

n = Racket::Racket.new
n.iface = "eth0"

n.l3 = Racket::L3::IPv4.new
n.l3.src_ip = ARGV[0] 
n.l3.dst_ip = ARGV[1]
n.l3.protocol = 0x11

n.l4 = Racket::L4::UDP.new
n.l4.src_port = 48484
n.l4.dst_port = 53

n.l5 = Racket::L5::DNS.new
n.l5.add_question(ARGV[2], 1, 1)
n.l4.payload = n.l5
n.l4.fix!(n.l3.src_ip, n.l3.dst_ip)
n.l4.payload = ""

f = n.sendpacket
n.layers.compact.each do |l|
  puts l.pretty
end
puts "Sent #{f}"
