#!/usr/bin/env ruby
#
# $Id$
#

require 'rubygems'
require 'racket'

include Racket
unless (ARGV.size == 3) 
  puts "Usage: #{$0} <srcip> <dstip> <code>"
  exit
end

n = Racket::Racket.new
n.iface = "eth0"

n.l3 = L3::IPv4.new
n.l3.src_ip = ARGV[0] 
n.l3.dst_ip = ARGV[1]
n.l3.protocol = 0x8

n.l4 = L3::EGP.new
n.l4.code = ARGV[2].to_i

f = n.sendpacket
n.layers.compact.each do |l|
  puts l.pretty
end
puts "Sent #{f}"
