#!/usr/bin/env ruby
#
# $Id$
#
# Given a source and destination IP address
# and a data size, spew all 65536 possible ICMPv6 

require 'rubygems'
require 'racket'

include Racket
if (ARGV.size != 3) 
  puts "Usage #{$0} <src_ip> <dst_ip> <icmp data size>"
  exit!
end


def tick 
  @it += 1
  @it = 0 if @it >= @ticks.size
  print "\r#{@ticks[@it]}"
  STDOUT.flush
end

def rand_icmp6(n)
  n.l4 = ICMPv6.new(Misc.randstring(20))
  n.l4.fix!(n.l3.src_ip, n.l3.dst_ip)
  n.sendpacket
  tick
end
  
@it = 0
@ticks = %w( / - \\ | )

n = Racket::Racket.new
n.iface = "eth0"
n.l2 = Ethernet.new(Misc.randstring(14))
n.l2.ethertype = 0x86DD
n.l3 = IPv6.new
n.l3.src_ip= ARGV[0].to_i
n.l3.dst_ip = ARGV[1].to_i
n.l3.nhead = 58

puts "Spewing..."
while (true)
  rand_icmp6(n)
end

# vim: set ts=2 et sw=2:
