#!/usr/bin/env ruby
#
# $Id$
#

require 'rubygems'
require 'racket'

if (ARGV.size != 4) 
  puts "Usage #{$0} <src_ip> <dst_ip> <igmp code> <gaddr>"
  exit!
end

n = Racket.new
n.l3 = IPv4.new

n.l3.src_ip = ARGV[0] 
n.l3.dst_ip = ARGV[1]
n.l3.protocol = 2 

n.l4 = IGMPv1.new
n.l4.type = ARGV[2].to_i
n.l4.gaddr = ARGV[3]

f = n.sendpacket
puts "Sent #{f} bytes"
