#!/usr/bin/env ruby
#
require 'rubygems'
require 'racket'

include Racket
if (ARGV.size != 5) 
  puts "Usage #{$0} <src_ip> <dst_ip> <op> <internal_port> <external_port>"
  exit!
end

n = Racket::Racket.new
n.iface = "eth0"
  n.l3 = L3::IPv4.new
  n.l3.src_ip= ARGV[0]
  n.l3.dst_ip = ARGV[1]
  n.l3.version = 0x4
  n.l3.hlen = 0x5
  n.l3.protocol = 0x11
  n.l3.flags = 0x0
  n.l3.foffset = 0x0
  n.l4 = L4::UDP.new
  n.l4.src_port = 5350
  n.l4.dst_port = 5351
  n.l5 = L5::NATPMPMappingRequest.new(:opcode => ARGV[2].to_i, :internal_port => ARGV[3].to_i, :external_port => ARGV[4].to_i)
  n.l5.opcode = ARGV[2].to_i
  n.l5.lifetime = 999999
  n.l4.payload = n.l5
  n.l4.fix!(n.l3.src_ip, n.l3.dst_ip)
  n.l4.payload = ""
  n.sendpacket
# vim: set ts=2 et sw=2:
