#!/usr/bin/env ruby
#
# $Id$
#

require 'rubygems'
require 'racket'

include Racket
n = Racket::Racket.new
n.iface = "eth0"

n.layers[2] = EightOTwoDotThree.new
n.layers[3] = LLC.new()
n.layers[4] = SNAP.new()
n.layers[4].pid = 0x010b

n.layers[5] = STP.new()
n.layers[5].version = 2

n.sendpacket
