#!/usr/bin/env ruby
#
# $Id$
#
# Send a DNS request

require 'rubygems'
require 'racket'

unless (ARGV.size == 3) 
  puts "Usage: $0 <srcip> <dstip> <domain>"
  exit
end

n = Racket::Racket.new
n.iface = "eth0"

n.l3 = IPv4.new
n.l3.src_ip = ARGV[0] 
n.l3.dst_ip = ARGV[1]
n.l3.protocol = 0x6
puts n.l3.class.describe
exit
