#!/usr/bin/env ruby
#
# $Id$
#

require 'rubygems'
require 'racket'

include Racket
unless (ARGV.size == 3) 
  puts "Usage: #{$0} <srcip> <dstip> <type>"
  exit
end

n = Racket::Racket.new
n.iface = "eth0"

n.l3 = L3::IPv4.new
n.l3.src_ip = ARGV[0] 
n.l3.dst_ip = ARGV[1]
n.l3.protocol = 112

n.l4 = L4::VRRP.new
n.l4.type = ARGV[2].to_i
n.l4.auth_type = 1
n.l4.add_ip("1.2.3.4")
n.l4.add_auth("haha")
#n.l4.payload = [ L3::Misc.ipv42long("1.2.3.4") ].pack("N")

f = n.sendpacket
n.layers.compact.each do |l|
  puts l.pretty
end
puts "Sent #{f}"
